ANALISIS RIB 
---

In [8]:
from monstry.Builder import Builder
from monstry.DataCleaner import DataCleaner

In [9]:
config_json = './rib_data/config/config.json'
builder = Builder( config_path = config_json)

Se ha creado usando un archivo de configuracion

In [10]:
rib_analisis = DataCleaner(builder, 'rib_ru_identificacion' )

Se ha cargado efectivamente el dataframe

        Informacion:
            _ get_completitud():
                Se obtienen la completutid de la tabla
            - get_exactitud():
                Se obtiene la exactitud de la tabla siempre y cuando los valores por default sean completados
                en el archivo de configuraciones o tengan un valor por defecto
            ----------------------------------------------------------------------------------------------------
            - get_resumen():
                Se obtiene un dataframe con el análisis de completitud y exactitud del dataset seleccionado

In [11]:
rib_analisis.get_completitud()
rib_analisis.completitud.to_csv('completitud.csv')

Analisis de completitud realizado teniendo en cuenta los valores por default
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD
0,insert_into_dl_timestamp,rib_ru_identificacion,100000,0,100000,100.000
1,notificacion_electronica,rib_ru_identificacion,100000,12224,87776,87.776
2,apodo,rib_ru_identificacion,100000,99202,798,0.798
3,fecha_creacion_beca,rib_ru_identificacion,100000,93401,6599,6.599
4,fecha_creacion_ts_2,rib_ru_identificacion,100000,99376,624,0.624
...,...,...,...,...,...,...
71,fecha_nacimiento,rib_ru_identificacion,100000,2230,97770,97.770
72,nombre,rib_ru_identificacion,100000,371,99629,99.629
73,apellido,rib_ru_identificacion,100000,371,99629,99.629
74,numero_documento,rib_ru_identificacion,100000,4551,95449,95.449
75,id_identificacion,rib_ru_identificacion,100000,0,100000,100.000

In [12]:
rib_analisis.completitud.to_csv('completitud.csv')

In [13]:
rib_analisis.get_exactitud()
rib_analisis.exactitud

Analisis de completitud realizado teniendo en cuenta los valores por default
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Se están usando valores por default para la validación de los datos
Para usar funciones customizadas de validación se deben determinar en el archivo de configuración json
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
⚠️WARNING:
	LA COLUMNA "numero_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "clase_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "vencimiento_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "fk_tipo_discapacidad" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "adjunta_certificado" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "norma_legal_designacion" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "descripcion_adicional_designac" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

                     COLUMNA  EXACTO  INEXACTO  PORCENTAJE DE EXACTITUD
0          id_identificacion  100000         0                  100.000
1                   telefono   51997      6802                   88.432
2           numero_documento   95449         0                  100.000
3                       edad   68821         0                  100.000
4                       cuil   58159         0                  100.000
..                       ...     ...       ...                      ...
71       fecha_creacion_ts_2     624         0                  100.000
72       fecha_creacion_beca    6599         0                  100.000
73  insert_into_dl_timestamp  100000         0                  100.000
74              razon_social      82       289                   22.102
75                     apodo     762        39                   95.131

[76 rows x 4 columns]

In [14]:
rib_analisis.get_resumen()

Analisis de completitud realizado teniendo en cuenta los valores por default
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Se están usando valores por default para la validación de los datos
Para usar funciones customizadas de validación se deben determinar en el archivo de configuración json
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
⚠️WARNING:
	LA COLUMNA "numero_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "clase_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "vencimiento_licencia_conducir" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "fk_tipo_discapacidad" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "adjunta_certificado" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "norma_legal_designacion" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
⚠️WARNING:
	LA COLUMNA "descripcion_adicional_designac" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD,EXACTO,INEXACTO,PORCENTAJE DE EXACTITUD
0,insert_into_dl_timestamp,rib_ru_identificacion,100000,0,100000,100.000,100000,0,100.000
1,notificacion_electronica,rib_ru_identificacion,100000,12224,87776,87.776,87776,0,100.000
2,apodo,rib_ru_identificacion,100000,99202,798,0.798,7,794,0.874
3,fecha_creacion_beca,rib_ru_identificacion,100000,93401,6599,6.599,6599,0,100.000
4,fecha_creacion_ts_2,rib_ru_identificacion,100000,99376,624,0.624,624,0,100.000
...,...,...,...,...,...,...,...,...,...
71,fecha_nacimiento,rib_ru_identificacion,100000,2230,97770,97.770,97770,0,100.000
72,nombre,rib_ru_identificacion,100000,371,99629,99.629,47316,52313,47.492
73,apellido,rib_ru_identificacion,100000,371,99629,99.629,73226,26403,73.499
74,numero_documento,rib_ru_identificacion,100000,4551,95449,95.449,95449,0,100.000
75,id_identificacion,rib_ru_identificacion,100000,0,100000,100.000,100000,0,100.000

In [15]:
rib_analisis.data_columnas()

El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar

[{'data': 'number',
  'dtype': 'int64',
  'type': 'int',
  'default': <function monstry.modules.funciones_generales.comprobando_numeros(variable)>,
  'columna': 'id_identificacion',
  'sample': '1028592'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'numero_documento',
  'sample': '21337246.0'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'apellido',
  'sample': 'GODOY'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'nombre',
  'sample': 'SILVIA'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_nacimiento',
  'sample': '1994-07-06 00:00:00.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'edad',
  'sample': '89.0'},
 {'data': 'alpha_numeric_text',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_alfanumerico(variable)>,
  'columna': 'telefono',
  'sample': '4302 7508'},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'telefono_alternativo',
  'sample': '15-55088591'},
 {'data': 'email',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_correo_valido(variable)>,
  'columna': 'correo_electronico',
  'sample': 'CELESTINAGOMEZ069@GMAIL.COM'},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'observaciones',
  'sample': ' En el día 12/08/2021, el sistema RIB ha inactivado el registro RIB-2014-1094779 con motivo: Defuncion notificado por sistema RCE - Registro Civil Electrónico'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'cuil',
  'sample': '20182910482.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_sexo',
  'sample': '8.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_situacion_conyugal',
  'sample': '8.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_tipo_documento',
  'sample': '7.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fecha_nacimiento_aproximada',
  'sample': '1.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_nacionalidad',
  'sample': '1.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_pais_anterior',
  'sample': '30.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'anio_ingreso_pais',
  'sample': '2006.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'anios_residencia_caba',
  'sample': '2003.0'},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'numero_licencia_conducir',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'clase_licencia_conducir',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'vencimiento_licencia_conducir',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'fk_tipo_discapacidad',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'adjunta_certificado',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'norma_legal_designacion',
  'sample': ''},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'descripcion_adicional_designac',
  'sample': ''},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_tipo_nacionalidad',
  'sample': '1.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_cp',
  'sample': '430712.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_cp',
  'sample': '202097.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_tipo_relacion_cp',
  'sample': '15.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_cp',
  'sample': '2014-01-23 18:32:23.000'},
 {'data': 'bool',
  'dtype': 'bool',
  'type': 'bool',
  'default': <function monstry.modules.funciones_generales.comprobando_booleanos(variable)>,
  'columna': 'rechazado_cp',
  'sample': '0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_beca',
  'sample': '310462.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_beca',
  'sample': '2014-03-21 17:24:40.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_adl',
  'sample': '43628.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_adl',
  'sample': '31086.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_adl',
  'sample': '2014-05-29 15:02:08.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_adl',
  'sample': '2014-05-29 15:02:08.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_ts',
  'sample': '10000882809500.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_ts',
  'sample': '100042814040.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_ts',
  'sample': '2014-06-19 16:03:35.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_ts',
  'sample': '2014-06-19 16:03:35.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_cops',
  'sample': '53004.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_cops',
  'sample': '251423.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_cops',
  'sample': '2014-08-29 11:56:23.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_cops',
  'sample': '2014-07-29 12:13:22.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_cops_2',
  'sample': '18230.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_cops_2',
  'sample': '8940.0'},
 {'data': 'no_determinado',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_no_determinado(variable)>,
  'columna': 'razon_social',
  'sample': 'ASOC. COOP. "A. BROWN" ES. N1 D.E.4º'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_tipo_persona_juridica',
  'sample': '1.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_ingresos_brutos',
  'sample': '3.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_condicion_ganancias',
  'sample': '2.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'fk_condicion_iva',
  'sample': '2.0'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'nombre_fantasia',
  'sample': 'LUPITA'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'nro_ingresos_brutos',
  'sample': '12716502.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_inicio_actividades',
  'sample': '1920-03-20 00:00:00.000'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'segundo_nombre',
  'sample': 'LIONEL'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'tercer_nombre',
  'sample': 'FELIX'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'segundo_apellido',
  'sample': 'ARIAS'},
 {'data': 'string',
  'dtype': 'object',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_strings(variable)>,
  'columna': 'tercer_apellido',
  'sample': 'CRUZ'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_agd',
  'sample': '6595.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_agd',
  'sample': '4479.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_agd',
  'sample': '2014-12-10 19:56:15.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_agd',
  'sample': '2014-12-10 19:56:15.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_690',
  'sample': '185478.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_690',
  'sample': '143444.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_690',
  'sample': '2014-12-12 18:15:33.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_690',
  'sample': '2014-12-12 18:15:33.000'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_persona_ts_2',
  'sample': '4422.0'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'id_hogar_ts_2',
  'sample': '29946.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_ultima_modificacion_ts_2',
  'sample': '2014-12-18 19:35:38.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_ts_2',
  'sample': '2014-12-18 19:35:38.000'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'fecha_creacion_beca',
  'sample': '2015-05-30 01:36:56.000'},
 {'data': 'number',
  'dtype': 'int64',
  'type': 'int',
  'default': <function monstry.modules.funciones_generales.comprobando_numeros(variable)>,
  'columna': 'apodo',
  'sample': '2'},
 {'data': 'decimal',
  'dtype': 'float64',
  'type': 'float',
  'default': <function monstry.modules.funciones_generales.comprobando_decimales(variable)>,
  'columna': 'notificacion_electronica',
  'sample': '0.0'},
 {'data': 'fechas',
  'dtype': 'datetime64',
  'type': 'str',
  'default': <function monstry.modules.funciones_generales.comprobando_fecha_general(variable)>,
  'columna': 'insert_into_dl_timestamp',
  'sample': '2023-04-25 14:43:28'}]

In [16]:
from functools import reduce 

reduce( lambda col_a,col_b: {**col_a,**col_b}, [ {data['columna']: data['dtype']} for data in rib_analisis.data_columnas()])

El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar
El dataframe no contiene registros para analizar

{'id_identificacion': 'int64',
 'numero_documento': 'float64',
 'apellido': 'object',
 'nombre': 'object',
 'fecha_nacimiento': 'datetime64',
 'edad': 'float64',
 'telefono': 'int64',
 'telefono_alternativo': 'int64',
 'correo_electronico': 'object',
 'observaciones': 'object',
 'cuil': 'float64',
 'fk_sexo': 'float64',
 'fk_situacion_conyugal': 'float64',
 'fk_tipo_documento': 'float64',
 'fecha_nacimiento_aproximada': 'float64',
 'fk_nacionalidad': 'float64',
 'fk_pais_anterior': 'float64',
 'anio_ingreso_pais': 'float64',
 'anios_residencia_caba': 'float64',
 'numero_licencia_conducir': 'object',
 'clase_licencia_conducir': 'object',
 'vencimiento_licencia_conducir': 'object',
 'fk_tipo_discapacidad': 'object',
 'adjunta_certificado': 'object',
 'norma_legal_designacion': 'object',
 'descripcion_adicional_designac': 'object',
 'fk_tipo_nacionalidad': 'float64',
 'id_persona_cp': 'float64',
 'id_hogar_cp': 'float64',
 'fk_tipo_relacion_cp': 'float64',
 'fecha_ultima_modificacion_cp': 'datetime64',
 'rechazado_cp': 'bool',
 'id_beca': 'float64',
 'fecha_ultima_modificacion_beca': 'datetime64',
 'id_persona_adl': 'float64',
 'id_hogar_adl': 'float64',
 'fecha_ultima_modificacion_adl': 'datetime64',
 'fecha_creacion_adl': 'datetime64',
 'id_persona_ts': 'float64',
 'id_hogar_ts': 'float64',
 'fecha_ultima_modificacion_ts': 'datetime64',
 'fecha_creacion_ts': 'datetime64',
 'id_persona_cops': 'float64',
 'id_hogar_cops': 'float64',
 'fecha_ultima_modificacion_cops': 'datetime64',
 'fecha_creacion_cops': 'datetime64',
 'id_persona_cops_2': 'float64',
 'id_hogar_cops_2': 'float64',
 'razon_social': 'object',
 'fk_tipo_persona_juridica': 'float64',
 'fk_ingresos_brutos': 'float64',
 'fk_condicion_ganancias': 'float64',
 'fk_condicion_iva': 'float64',
 'nombre_fantasia': 'object',
 'nro_ingresos_brutos': 'float64',
 'fecha_inicio_actividades': 'datetime64',
 'segundo_nombre': 'object',
 'tercer_nombre': 'object',
 'segundo_apellido': 'object',
 'tercer_apellido': 'object',
 'id_persona_agd': 'float64',
 'id_hogar_agd': 'float64',
 'fecha_ultima_modificacion_agd': 'datetime64',
 'fecha_creacion_agd': 'datetime64',
 'id_persona_690': 'float64',
 'id_hogar_690': 'float64',
 'fecha_ultima_modificacion_690': 'datetime64',
 'fecha_creacion_690': 'datetime64',
 'id_persona_ts_2': 'float64',
 'id_hogar_ts_2': 'float64',
 'fecha_ultima_modificacion_ts_2': 'datetime64',
 'fecha_creacion_ts_2': 'datetime64',
 'fecha_creacion_beca': 'datetime64',
 'apodo': 'object',
 'notificacion_electronica': 'float64',
 'insert_into_dl_timestamp': 'datetime64'}